name: detect_false_gps
description: "Faz detecção nativa de GPS falso no iPhone."
version: 0.0.3
repository: https://github.com/kaiquecruz/detect_false_gps
issue_tracker: https://github.com/kaiquecruz/detect_false_gps/issues

environment:
  sdk: ^3.9.2
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: DetectFalseGpsPlugin
