name: detect_false_gps
description: "A new Flutter plugin project."
version: 0.0.1
repository: https://github.com/developermanishdevan/developer_mode_finder
issue_tracker: https://github.com/developermanishdevan/developer_mode_finder/issues

environment:
  sdk: ^3.9.2
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: DetectFalseGpsPlugin